spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/redis?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: song
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cache: trace
